### PR TITLE
Added C++ solution and improved the ReadMes

### PR DESCRIPTION
**Pull request by LarsDitt**

### CODE REVIEW

**Comment by matchRos** [comment]
please mark all python nodes as executable

**Comment by Heenne** [comment]
Sorry, I didn't specify it clearly enough. The c++ files must be listed in cmake file of the move_mir_tasks so when I am executing `catkin build` the c++ solution is built.
So just move the content of the cmake in the solution folder to the "move_mir_tasks" package cmake.
Also change the naming in the cmake, it is not good to just name it "package_node". Better would be "solution_2_cpp_node" or something like it.

**Comment by LarsDitt** [comment]
Please have a look at the CMakeLists.txt in the solution folder of a task.

I've deleted the CMakeLists.txt in the move_mir_tasks folder to avoid confusion.

**Comment by Heenne** [comment]
General functionality is implemented. For bugs or improvements an issue will be created.

**Pull request merged**
